### ISSUE TITLE
ipm.ipynb code seems to have problems

### ISSUE THREAD

**Issue by Piyushi-0** [sylvaincom/comparison-distributions#1]
Hi Sylvaincom, Thanks for sharing the codes, it introduced me to the PuLP library.
I think there are small issues with the functions construct_b  & kantorovich_metric. I am replacing the parts of your code with my suggestions in bold. Kindly review:

1. ```
def construct_b(X_p, X_q):
    
    X = np.concatenate((X_p, X_q), axis=0)
    N = len(X)
    
    b_part = []
    for i in range(N):
        for j in range(i+1, N):
            b_part.append(rho(X[i], X[j]))
    
    # **We duplicate each row of b_part to obtain a list of size N*(N-1)**
    b = []
    for i in range(**len(b_part)**):
        b.append(b_part[i])
        b.append(b_part[i])
    
    return b

```2. Accordingly number of constraints ie. 'p' in kantorovich_metric function will change
```
def kantorovich_metric(X_p, X_q):
    
    X = np.concatenate((X_p, X_q), axis=0)
    m = len(X_p)
    n = len(X_q)
    N = m+n
    
    c = construct_c(X_p, X_q)
    b = construct_b(X_p, X_q)
    M = construct_M(X_p, X_q)
    
    prob = LpProblem("LP_problem_for_estimating_the_Kantorovich_metric", LpMaximize)
    a = LpVariable.matrix("a", list(range(N)))
    prob += lpDot(c, a)
    p = **M.shape[0]**
    for i in range(p):
        prob += lpDot(M[i], a) <= b[i]
    prob.solve()

    return value(prob.objective)
```

**Comment by sylvaincom** [comment]
Hi @Piyushi-0 :smiley:

Thanks for using my code and providing some useful feedback! Indeed, there was a mistake as `p=N*(N-1)`. Would you like to create a pull request with the modifications? Otherwise, I can push the code myself, as I also need to modify other parts of the code and I understand that pull requests are not efficient with the Jupyter Notebook format.

On another topic, feel free to fully use the Markdown environment that can for example [display beautiful Python code](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) such as:
```python
def some_function(x):
    return 2*x+1
```

Best,
Sylvain

**Comment by Piyushi-0** [comment]
Thanks for sharing Sylvain. I'll be happy to share a pull request. I also implemented the Wasserstein estimator using some other library & found it to be faster. I'll share that too.

Regards,
Piyushi

**Comment by sylvaincom** [comment]
Hi @Piyushi-0 

Perfect, thanks a lot!

Best,
Sylvain

**Comment by sylvaincom** [comment]
Hi @Piyushi-0 

I hope you are doing well. Is the pull request still in sight? Thanks again for pointing out the mistake!

Best,
Sylvain

**Comment by Piyushi-0** [comment]
Hi Sylvain,
I deeply apologise for the delay. I have been busy with multiple things. I expect to be very busy for atleast a month more. If you wish to make the changes, please go ahead. Sorry for the inconvenience caused.

Regards,
Piyushi

**Comment by sylvaincom** [comment]
Hi @Piyushi-0

Thanks for your quick response. No problem at all, I perfectly understand. I will try to make the changes by the end of this week myself then. Thanks again for pointing out the mistake.

I wish you good luck with your projects!
Sylvain

**Comment by Piyushi-0** [comment]
Thank you very much, Sylvain.
